---
- name: My dream env
  hosts: localhost
  roles:
    - role: tools
      become: true
      become_method: ansible.builtin.sudo
      become_user: root
    - role: settings
      become: false
      become_user: "{{ ansible_env.USER }}"
