---
roles:
  - src: gantsign.oh-my-zsh
  - src: diodonfrost.p10k
  - src: gantsign.visual-studio-code
  - src: geerlingguy.nodejs
  - src: geerlingguy.php
  - src: geerlingguy.composer

collections:
  - name: community.general
    source: https://github.com/ansible-collections/community.general
    type: git
    version: 8.2.0
