---
- name: "Updating apt repo/cache (apt update)"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: "Upgrade all packages (apt upgrade)"
  apt: upgrade=yes force_apt_get=yes

- name: "Install my list of tools"
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ app_list }}"