---
- block:
  - name: apt
    include_tasks: apt.yml
  tags: "apt"

- block:
  - name: gem
    include_tasks: gem.yml
  tags: "gem"

- block:
  - name: nodejs
    include_tasks: nodejs.yml
  tags: "nodejs"

- block:
  - name: php
    include_tasks: php.yml
  tags: "php"

- block:
  - name: composer
    include_tasks: composer.yml
  tags: [ "php", "composer" ]

- block:
  - name: oh-my-zsh
    include_tasks: oh-my-zsh.yml
  tags: "oh-my-zsh"

- block:
  - name: Install VSCode with extensions
    include_tasks: vs_code.yml
  tags: "vs_code"

# - block:
#   - name: rust/cargo install
#     include_tasks: cargo.yml
#   tags: [ "cargo", "rust" ]

# - block:
#   - name: Cargo packages
#     include_tasks: cargo_packages.yml
#   tags: [ "cargo", "rust" ]