---
- name: Install Node.js dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - software-properties-common

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    state: present

- name: Add NodeSource repository with the latest version
  vars:
    # I didn't find an API point where I can get the latest Node.js version
    # so I'm hardcoding it here. You can find details here:
    # https://nodejs.org/en/about/previous-releases
    nodejs_version: 20
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Install build-essential
  apt:
    name: build-essential
    state: latest