---
- name: Install Visual Studio Code
  become: false
  import_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ ansible_env.SUDO_USER }}"
        visual_studio_code_extensions:
          - bibhasdn.unique-lines # Manage line uniqueness in files.
          - GitHub.copilot # AI-powered code completion tool.
          - GitHub.copilot-chat # Extension with chat features for Copilot.
          - GitHub.github-vscode-theme # GitHub's official VSCode theme.
          - github.vscode-github-actions # GitHub Actions support in VSCode.
          - GitHub.vscode-pull-request-github # GitHub pull request integration.
          - helixquar.randomeverything # Generate random content in the editor.
          - johnpapa.vscode-peacock # Customize VSCode workspace colors.
          - mutantdino.resourcemonitor # Monitor VSCode resource usage.
          - neilbrayfield.php-docblocker # Generate PHP docblocks.
          - neptunedesign.vs-sequential-number # Manage sequential numbers.
          - netcorext.uuid-generator # Generate and insert UUIDs.
          - phplasma.csv-to-table # Convert CSV to formatted table.
          - redhat.ansible # Ansible support in VSCode.
          - SanderRonde.phpstan-vscode # Integrate PHPStan for static analysis.
          - shevaua.phpcs # PHP CodeSniffer integration.
          - waderyan.gitblame # View Git blame information.
        visual_studio_code_settings_overwrite: false

- name: Copy my keybinders.json
  copy:
    src: files/keybindings.json
    dest: "{{ ansible_env.SUDO_USER_HOME }}/.config/Code/User/keybindings.json"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0664"