---
# This should be improved due the fact that it will remove all aliases all the time even if they already exist
- name: Remove specified aliases from .zshrc
  shell: |
    for ALIAS in {{ aliases | map(attribute='name') | list | join(' ') }}
    do
      sed -i "/^[[:space:]]*alias $ALIAS=/d" ~/.zshrc
    done
  args:
    executable: /bin/bash

- name: Add new aliases
  lineinfile:
    path: ~/.zshrc
    line: "alias {{ item.name }}=\"{{ item.command }}\""
  with_items: "{{ aliases }}"
