---
- name: Check if directories exist
  stat:
    path: "{{ item }}"
  register: dir_check
  with_items: "{{ path }}"
  ignore_errors: true

- name: Add paths to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "export PATH=$PATH:{{ item.item }}"
  loop: "{{ dir_check.results }}"
  when: item.stat.exists
  tags: update_zshrc
