---
- name: Updating apt repo/cache (apt update)
  ansible.builtin.apt:
    update_cache: "yes"
    force_apt_get: "yes"
    cache_valid_time: "3600"

- name: Upgrade all packages (apt upgrade)
  ansible.builtin.apt:
    upgrade: "yes"
    force_apt_get: "yes"

- name: Install my list of tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools_app_list }}"
  when: ansible_os_family == "Debian"
