---
- name: Install Node.js dependencies
  ansible.builtin.import_role:
    name: geerlingguy.nodejs
  vars:
    nodejs_version: 20.x
    nodejs_npm_global_packages:
      - nushell
      - diff-so-fancy
      - "@githubnext/github-copilot-cli"
